// This file was generated by @wuguishifu/page-parser.
// Feel free to remove these comments and to directly modify this file as you wish.

import Split from '@/components/Split';
import Card from '@/components/Card';

export default function Page() {
  return (
    <>
      <Split>
        <Card className="bg-red-200" type="hello">
          <p dangerouslySetInnerHTML={{ __html: `<strong>Bold Text</strong>` }} />
        </Card>
        <Card>
          <p dangerouslySetInnerHTML={{ __html: `<em>Italicized Text</em>` }} />
        </Card>
      </Split>
      <Split className="mt-8">
        <Card className="bg-green-200">
          <p dangerouslySetInnerHTML={{ __html: `<u>Underlined Text</u>` }} />
          <p dangerouslySetInnerHTML={{ __html: `hi hello` }} />
          <p dangerouslySetInnerHTML={{ __html: `one space two {space}` }} />
          <p dangerouslySetInnerHTML={{ __html: `three space` }} />
          <p dangerouslySetInnerHTML={{ __html: `hi everyone` }} />
          <a href="https://bo-bramer.com" className="text-gray-400 underline">Bo Bramer.com</a>
        </Card>
        <Card className="bg-purple-200">
          <p dangerouslySetInnerHTML={{ __html: `<strong><em>Bold and Italicized Text</strong></em>` }} />
          <img className="h-8" src="vite.svg" />
        </Card>
      </Split>
    </>
  );
};